version: "3.9"

services:
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - "./db/local-docker-volume:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "./src:/var/www/html/bedrock"
      - "./chore/php.conf.ini:/usr/local/etc/php/conf.d/php.conf.ini"
      - "./chore/apache-development.conf:/etc/apache2/sites-available/000-default.conf"
    environment:
      - APACHE_RUN_USER="www-data"
      - APACHE_RUN_GROUP="www-data"
      - WORDPRESS_DB_HOST="db:3306"
      - WORDPRESS_DB_USER="wordpress"
      - WORDPRESS_DB_PASSWORD="wordpress"
      - WORDPRESS_DB_NAME="wordpress"

  wp-cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    environment:
      - APACHE_RUN_USER="www-data"
      - APACHE_RUN_GROUP="www-data"
      - WP_CLI_PACKAGES_DIR=src/.wp-cli/
      - WP_CLI_CONFIG_PATH=src/config.yml
    volumes:
      - "./src:/var/www/html/bedrock"
      - "./db:/var/www/html/db:rw"
